set -g mouse on

# Copy selection to system clipboard
set -s copy-command 'xclip -selection clipboard'
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'
bind-key -T copy-mode    Enter send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'
